name: Vercel Production Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel
        run: |
          cd frontend
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  notify:
    needs: deploy-production
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify success
        if: ${{ needs.deploy-production.result == 'success' }}
        run: echo "Frontend deployed successfully to Vercel production environment"
        
      - name: Notify failure
        if: ${{ needs.deploy-production.result == 'failure' }}
        run: echo "Frontend deployment to Vercel production environment failed"